### ISSUE TITLE
feature request dump, multi-monitor support, keybindings, mouse support....

### ISSUE THREAD

**Issue by bijang** [stumpwm/mahogany#5]
apologies, I'm going to put a few feature requests as issues up, as they come to me, (to get them out of my system), these are my ideas which I have no programming capacity to enact or know if they're possible even... :)

I believe most of the feature improvements are roughly written in the stumpwm wishlist and  your outline for the mahogany project, and faster load, imporved performace, reduced memory usage and modularity are a given I think... just wanted to throw a few things in, bear with me...

- multimonitor support for mahogany ie capable of coping not just with multiple, but comcurrent use of monitors of varying ratios and resolutions

- emacs and vim keybinding;  taking the next browser project as an example, emacs-like and vim-like options, of sane defaults, both built in from the outset, (perhaps with some consistancy between projects if that were appropriate to ease the induction for newcomers)

- emacs integration... so there's nothing someone on exwm would complain about on migration

- hybrid, ie options of dynamic (tiling, stacked, tabbed, etc) and manual tiling, so there's nothing an ex-i3/sway/other refugee would miss out on (after some hopefully not too challenging config), as much as a stump user would feel at home; 

- easy themability, (if that's a word), it's important to accomodate, eg leftwm put this as an upfront selling point 

- finally, you have in already mentioned I believe, better gui inteaction, proper floating windows, mouse interaction etc,...  extending the interaction of the mouse with the tiling facility, eg draggin borders to resize tiles, snapping to fill a gap, getting a tile to float, ie a more extensive and smoother way of having the mouse do tiling, might be strange request for a typically keyboard driven paradigm but it;s so obvious a need that's ignored, fleshing out this side, which is kind of half heartedly done in for eg i3 (or kde or windows for that matter), would really be to the benefit of this (or any tiling wm) project; ie excellent keyboard driven and (decently-at-least) mouse driven

**Comment by sdilts** [comment]
Thanks for the input! Many of these features should eventually make it in to Mahogany.

This should be split up into separate issues, or added to the [features document](https://github.com/stumpwm/mahogany/blob/master/doc/devel/features.md), but I'll address some of them here:
1. Multi monitor support: Of course, multiple monitors will be supported. However, things like output mirroring won't be officially supported until wlroots and/or sway provide a canonical implementation of how this should be done. Please see the related Sway issue: [Output mirroring and complex layout configurations](https://github.com/swaywm/sway/issues/1666).  
2. Keybindings: I'm in the process of writing out a scheme that will make enabling and disabling sets of keybindings really easy. If you have any ideas about this, I'd be happy to hear about them.
3. More Emacs integration: Could you explain further? 
4. Some improvements to tiling windows is planned. I'm not comfortable committing to anything other than having frame trees that can have multiple children instead of Stumpwm's 2. I'm also exploring how to quickly switch between frame layouts. 
5. Themability: Are you talking about setting colors, or something more advanced? I'd love to hear a proposal on how we should do this or what we should support.
6. Floating windows: I've created a separate issue for this: https://github.com/stumpwm/mahogany/issues/7
7. Mouse control: I'd love to hear a proposal about this, but I do think it is possible to take this too far.

Once the proper, separate issues are filled, this issue should be closed.

**Comment by sdilts** [comment]
Thanks for splitting this into multiple issues!
